apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector
  namespace: selfheal
spec:
  replicas: 1            # single-leader for now. later add leader-election
  selector:
    matchLabels:
      app: detector
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
        - name: detector
          image: anveshshetty/detector:latest
          imagePullPolicy: IfNotPresent
          args: ["/app/config.yaml"]
          ports:
            - containerPort: 9100
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: detector-config
