apiVersion: batch/v1
kind: Job
metadata:
  name: hey-load
  namespace: selfheal
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hey
          # Simple HTTP load generator
          image: docker.io/emicklei/hey:latest
          args:
            # 45s test, 30 conns, 20 qps per worker → decent pressure but not insane
            - "-z"
            - "45s"
            - "-c"
            - "30"
            - "-q"
            - "20"
            - "http://app-svc.selfheal.svc.cluster.local/work?ms=500"
  backoffLimit: 0
