apiVersion: v1
kind: Pod
metadata:
  name: netem
  namespace: selfheal
spec:
  containers:
  - name: netem
    image: nicolaka/netshoot
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
