apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-sa
  namespace: selfheal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-role
  namespace: selfheal
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-rolebinding
  namespace: selfheal
subjects:
  - kind: ServiceAccount
    name: chaos-sa
    namespace: selfheal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaos-role
